version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turismo-app
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Guepardo32
      MYSQL_DATABASE: turismo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
